.TH VBS_LS 1 "JUNE 2013" Linux "User Manuals"
.SH NAME
vbs_ls \- List recorded sessions
.SH SYNOPSIS
.B vbs_ls [-s]
.SH DESCRIPTION
.B vbs_ls
List all available recordings in the data directories
.SH OPTIONS
.IP -s
Also calculate total size of each recording. Note this is slow.
.SH AUTHOR
Tomi Salminen <tlsalmin at gmail dot com>
.SH "SEE ALSO"
.BR vbs_rm (1),
