.TH VBS_RM 1 "JUNE 2013" Linux "User Manuals"
.SH NAME
vbs_rm \- Removes recordings from data directories
.SH SYNOPSIS
.B vbs_ls 
.I recording
.SH DESCRIPTION
.B vbs_rm
Removes recording or wild card recordings from data directories
.SH AUTHOR
Tomi Salminen <tlsalmin at gmail dot com>
.SH "SEE ALSO"
.BR vbs_ls (1),
