#!/bin/bash
RECORDING=$1

SUM=0

for i in /mnt/disk*
do
  if [ -d $i/$RECORDING ]
  then
    for j in $i/$RECORDING/*
    do
      SUM=$(($SUM+`stat $j -c %s`))
    done
  fi
done

echo $SUM B, $(($SUM/(1024*1024)))MB, $((SUM/(1024*1024*1024)))GB
