#!/bin/bash
RECNAME=$1
ROOTDIRS=/mnt/disk
#ONECFG=`find ${ROOTDIRS%/*} | grep ${RECNAME}.cfg`
#Find is sooo slow
ONECFG=/mnt/unionfs/${RECNAME}/${RECNAME}.cfg
PSIZE=`cat $ONECFG |grep packet_size|awk '{print $3}'|sed 's/[^0-9]//g'`
echo $PSIZE

for j in `find /mnt/unionfs/${RECNAME}/ | grep -v cfg |sort -n -t . -k 2`
do
  #if [ -e "$j" ]
  #then
    check_64_seq $j $PSIZE
  #fi
done
