#!/bin/bash

SCRIPTNAME=vbs_shutdown
scriptPath=${0%$SCRIPTNAME}
if [ -z "$scriptPath" ]
then
  #invoked from PATH
  scriptPath=$(which $0)
  scriptPath=${scriptPath%$SCRIPTNAME}
fi
source ${scriptPath}vbs_common_functions

echo "shutdown = 
{
};
" >> $SCHEDULE
