#!/bin/bash

usage()
{
cat << EOF
usage: $0 <recording name> <destination host or ip>

This script queues a streaming for the vlbistreamer daemon
EOF
}

LOGFILE=temp/vlbistreamer.log

vbs_queue $@ -m s
if [ $? == 1 ]
then
  echo ""
  usage
  echo ""
  echo "Errors in parameters of streaming $RECNAME" >> $LOGFILE
else
  #TODO: What date format people want?
  echo "`date` :Added streaming named $RECNAME to send to $DUR" >> $LOGFILE
fi
