#!/bin/bash

usage()
{
cat << EOF
usage: $0 <recording name> <start time> <duration>

This script queues a recording for the vlbistreamer daemon
EOF
}
#Both should update at installed location after make install
SCHEDULE=temp/vlbischedule
LOGFILE=temp/vlbistreamer.log
RECNAME=$1
DUR=$2
STIME=$3

if [ -z "$RECNAME" ] || [ -z "$DUR" ]
then
  usage
  exit  -1
fi
if [ -z "$STIME" ]
then
  echo "Not setting stamp of first packet. Starting immediately"
fi

echo "$RECNAME =
{
  time = $((DUR))L;
  starting_time = $((STIME))L;
  record = 1;
};
" >> $SCHEDULE
#TODO: What date format people want?
echo "`date`:Added recording named $RECNAME to record for $DUR s" >> $LOGFILE
