#!/bin/bash

usage()
{
cat << EOF
usage: $0 <recording name> <destination host or ip>

This script queues a streaming for the vlbistreamer daemon
EOF
}

SCRIPTNAME=vbs_send
scriptPath=${0%$SCRIPTNAME}
if [ -z "$scriptPath" ]
then
  #invoked from PATH
  scriptPath=$(which $0)
  scriptPath=${scriptPath%$SCRIPTNAME}
fi
source ${scriptPath}vbs_common_functions


vbs_queue $@ -m s
if [ $? == 1 ]
then
  echo ""
  usage
  echo ""
  echo $(date --rfc-3339=seconds) "Errors in parameters of streaming $RECNAME"
else
  echo "Streaming added OK"
fi
