#!/bin/bash
usage()
{
cat << EOF
$0 <sched_name>

$0 Removes the sched_name scheduled event from the schedule
EOF
}

SCRIPTNAME=vbs_schedulerm
scriptPath=${0%$SCRIPTNAME}
if [ -z "$scriptPath" ]
then
  #invoked from PATH
  scriptPath=$(which $0)
  scriptPath=${scriptPath%$SCRIPTNAME}
fi
source ${scriptPath}vbs_common_functions

if [ -z "$1" ]
then
  usage
  exit 1
fi

RECNAME=$1

#Recname is always first
(
flock  -x 201

for i in $(grep $RECNAME $SCHEDULE -n|cut -d ':' -f 1)
do
  REALSTART=$(($i-2))
  END=$(tail -n +${REALSTART} $SCHEDULE | grep -n -m 1 "}" | cut -d ':' -f 1)
  END=$(($REALSTART+$END-1))
  sed -i.bak -e "${REALSTART},${END}d" $SCHEDULE
  #echo $REALSTART $END
done

) 201>$SCHEDLOCKFILE
