#!/bin/bash

usage()
{
cat << EOF
usage: $0 <recording name> <duration>

This script queues a recording for the vlbistreamer daemon
EOF
}
#Both should update at installed location after make install
LOGFILE=temp/vlbistreamer.log

vbs_queue $@ -m r

if [ $? == 1 ]
then
  echo ""
  usage
  echo ""
  echo "Errors in parameters of recording $RECNAME" >> $LOGFILE
else
  #TODO: What date format people want?
  echo "`date`:Added recording named $RECNAME to record for $DUR s" >> $LOGFILE
fi
exit 0
